# config/ecommerce/ecommerce.yaml

pimcore_ecommerce_framework:
    index_service:
        tenants:
            default:
                worker_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Worker\DefaultMysql
                config_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Config\DefaultMysql

                # 1) Tell the tenant which classes to index
                config_options:
                    class_definitions:
                        - { className: 'Pimcore\\Model\\DataObject\\Product' }

                # 2) MySQL-friendly attribute definitions
                attributes:
                    id:
                        type: int
                        filter_group: string
                    sku:
                        type: "varchar(255)"
                        filter_group: string
                    name:
                        type: "varchar(255)"
                        filter_group: string
                    description:
                        type: text
                    price:
                        type: double
                        filter_group: number
                    stock:
                        type: int
                        filter_group: number
                    status:
                        type: "varchar(255)"
                        filter_group: string
                    categoryNames:
                        type: text
                        filter_group: multiselect
                    brandName:
                        type: "varchar(255)"
                        filter_group: string