pimcore_ecommerce_framework:
    index_service:
        default_tenant: OpenSearch
        tenants:
            OpenSearch:
                enabled: true
                worker_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Worker\OpenSearch\DefaultOpenSearch
                config_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Config\OpenSearch
                config_options:
                    opensearch_client_name: 'default'
                    client_config:
                        indexName: 'products'
                        logging: true
                        host: 'opensearch'
                        port: 9200
                        scheme: 'http'
                        username: 'admin'
                        password: 'YouongPrStrassword123!'
                        ssl_verification: false
                    index_settings:
                        number_of_shards: 1
                        number_of_replicas: 1
                placeholders:
                    '%%locale%%': 'en'
                search_attributes:
                    - name^3
                    - sku
                    - brandName
                    - categoryNames
                attributes:
                    id:
                        locale: '%%locale%%'
                        type: integer
                        filter_group: string
                    sku:
                        locale: '%%locale%%'
                        type: keyword
                        filter_group: string
                    name:
                        locale: '%%locale%%'
                        type: keyword
                        filter_group: string
                    price:
                        locale: '%%locale%%'
                        type: long
                        filter_group: number
                    stock:
                        type: integer
                        filter_group: number
                    status:
                        locale: '%%locale%%'
                        type: keyword
                        filter_group: string
                    categoryNames:
                        locale: '%%locale%%'
                        type: keyword
                        filter_group: multiselect
                    brandName:
                        type: keyword
                        filter_group: relation
                        interpreter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\ObjectValue
                        interpreter_options:
                            target:
                                fieldname: name
                                locale: '%%locale%%'
    
    filter_service:
        tenants:
            OpenSearch:
                filter_types:
                    FilterInputfield:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\Input
                        template: 'product/filters/input.html.twig'

                    FilterNumberRange:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\NumberRange
                        template: 'product/filters/numberrange.html.twig'

                    FilterNumberRangeSelection:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\NumberRangeSelection
                        template: 'product/filters/numberrange_select.html.twig'

                    FilterSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\Select
                        template: 'product/filters/select.html.twig'

                    FilterSelectFromMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\SelectFromMultiSelect
                        template: 'product/filters/select.html.twig'

                    FilterMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\MultiSelect
                        template: 'product/filters/multi_select.html.twig'

                    FilterMultiSelectFromMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\MultiSelectFromMultiSelect
                        template: 'product/filters/multi_select.html.twig'

                    FilterMultiRelation:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\MultiSelectRelation
                        template: 'product/filters/multi_relation.html.twig'

                    FilterCategory:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\SelectCategory
                        template: 'product/filters/select_category.html.twig'

                    FilterRelation:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\SelectRelation
                        template: 'product/filters/object_relation.html.twig'

    cart_manager:
        tenants:
            _defaults:
                cart_manager_id: Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\MultiCartManager

                cart:
                    factory_id: Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\CartFactory
                    
                    factory_options:
                        cart_class_name: Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\Cart
                        guest_cart_class_name: Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\SessionCart
        
            default:   
                price_calculator:
                    modificators:
                        shipping:
                            class: Pimcore\Bundle\EcommerceFrameworkBundle\CartManager\CartPriceModificator\Shipping
                            options:
                                charge: "5.90"

            noShipping: ~

    price_systems:
        default:
            id: Pimcore\Bundle\EcommerceFrameworkBundle\PriceSystem\AttributePriceSystem

    availability_systems:
        default:
            id: Pimcore\Bundle\EcommerceFrameworkBundle\AvailabilitySystem\AvailabilitySystem

    checkout_manager:
        tenants:
            _defaults:
                factory_id: Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\CheckoutManagerFactory

                factory_options:
                    class: \Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\V7\CheckoutManager
                    handle_pending_payments_strategy: Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\V7\HandlePendingPayments\CancelPaymentOrRecreateOrderStrategy

                commit_order_processor:
                    id: Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\V7\CommitOrderProcessor
                    
                    options:
                        confirmation_mail: /en/emails/order-confirmation
                
                steps:
                    deliveryaddress:
                        class: \App\CheckoutManager\DeliveryAddress
                        
                    confirm:
                        class: \App\Ecommerce\Checkout\Confirm

    payment_manager:
        payment_manager_id: Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\PaymentManager

        providers:
            datatrans:
                provider_id: Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\Payment\Datatrans

                profile: sandbox

                profiles:
                    sandbox:
                        merchant_id: 1000011011
                        sign: 30916165706580013
                        use_digital_signature: false
                    live:
                        merchant_id: merchant_id_id
                        sign: sign_id
                        use_digital_signature: false
                        mode: live

            ogone:
                provider_id: Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\Payment\OGone
                profile: sandbox
                profiles:
                    sandbox:
                        secretIn: D343DDFD3434
                        secretOut: D343DDFD3434
                        pspid: MyTestAccount
                        mode: sandbox
                    live:
                        secretIn: D343DDFD3434
                        secretOut: D343DDFD3434
                        pspid: MyLiveAccount
                        mode: live                       
            mpay24:
                provider_id: Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\Payment\Mpay24Seamless
                profile: testsystem
                profiles:
                  _defaults:
                      partial: Shared/Includes/Shop/Payment/paymentMethods.html.php
                      payment_methods:
                          cc:
                          paypal:
                          sofort:
                          invoice:
                  testsystem:
                      merchant_id: 95387
                      password: 7&jcQ%v6RB
                      testSystem: true
                      debugMode: true
                  live:
                      merchant_id: todo
                      password: todo
                      testSystem: false
                      debugMode: false                  
            hobex:
                    provider_id: Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\Payment\Hobex                    
                    profile: sandbox
                    profiles:
                        sandbox:
                            entityId: '8a829418530df1d201531299e097175c'
                            authorizationBearer: 'OGE4Mjk0MTg1MzBkZjFkMjAxNTMxMjk5ZTJjMTE3YWF8ZzJnU3BnS2hLUw=='
                            testSystem: true
                            payment_methods:
                                - VISA
                                - MASTER
                                - SOFORTUEBERWEISUNG
                                - SEPA     