pimcore_ecommerce_framework:
    index_service:
        tenants:
            OpenSearch:
                enabled: true
                worker_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Worker\OpenSearch\DefaultOpenSearch
                config_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Config\OpenSearch
                config_options:
                    opensearch_client_name: 'default'
                    client_config:
                        indexName: '%env(OPENSEARCH_INDEX)%'
                        logging: true
                        host: 'opensearch'  # Changed from default 'localhost'
                        port: 9200
                        scheme: 'https'     # Added scheme since you're using HTTPS
                        username: '%env(OPENSEARCH_USERNAME)%'
                        password: '%env(OPENSEARCH_PASSWORD)%'
                        ssl_verification: false  # Disable SSL verification for self-signed certs
                    index_settings:
                        number_of_shards: 1
                        number_of_replicas: 1
                search_attributes:
                    - name^3
                    - description
                    - sku
                    - brandName
                    - categoryNames
                attributes:
                    id:
                        type: integer
                        filter_group: string
                    sku:
                        type: keyword
                        filter_group: string
                    name:
                        type: text
                        filter_group: string
                    description:
                        type: text
                    price:
                        type: double
                        filter_group: number
                    stock:
                        type: integer
                        filter_group: number
                    status:
                        type: keyword
                        filter_group: string
                    categoryNames:
                        type: keyword
                        filter_group: multiselect
                    brandName:
                        type: keyword
                        filter_group: relation
                        interpreter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\ObjectValue
                        interpreter_options:
                            target:
                                fieldname: name