pimcore_ecommerce_framework:
    index_service:
        default_tenant: OpenSearch
        tenants:
            OpenSearch:
                enabled: true
                worker_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Worker\OpenSearch\DefaultOpenSearch
                config_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Config\OpenSearch
                config_options:
                    opensearch_client_name: 'default'
                    client_config:
                        indexName: 'products'
                        logging: true
                        host: 'opensearch'
                        port: 9200
                        scheme: 'http'
                        username: 'admin'
                        password: 'YouongPrStrassword123!'
                        ssl_verification: false
                    index_settings:
                        number_of_shards: 1
                        number_of_replicas: 1
                placeholders:
                    '%%locale%%': 'en'
                search_attributes:
                    - name^3
                    - sku
                    - brandName
                    - categoryNames
                attributes:
                    id:
                        locale: '%%locale%%'
                        type: integer
                        filter_group: string
                    sku:
                        locale: '%%locale%%'
                        type: keyword
                        filter_group: string
                    name:
                        locale: '%%locale%%'
                        type: keyword
                        filter_group: string
                    price:
                        locale: '%%locale%%'
                        type: long
                        filter_group: number
                    stock:
                        type: integer
                        filter_group: number
                    status:
                        locale: '%%locale%%'
                        type: keyword
                        filter_group: string
                    categoryNames:
                        locale: '%%locale%%'
                        type: keyword
                        filter_group: multiselect
                    brandName:
                        type: keyword
                        filter_group: relation
                        interpreter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Interpreter\ObjectValue
                        interpreter_options:
                            target:
                                fieldname: name
                                locale: '%%locale%%'
    
    filter_service:
        tenants:
            OpenSearch:
                filter_types:
                    FilterInputfield:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\Input
                        template: 'product/filters/input.html.twig'

                    FilterNumberRange:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\NumberRange
                        template: 'product/filters/numberrange.html.twig'

                    FilterNumberRangeSelection:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\NumberRangeSelection
                        template: 'product/filters/numberrange_select.html.twig'

                    FilterSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\Select
                        template: 'product/filters/select.html.twig'

                    FilterSelectFromMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\SelectFromMultiSelect
                        template: 'product/filters/select.html.twig'

                    FilterMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\MultiSelect
                        template: 'product/filters/multi_select.html.twig'

                    FilterMultiSelectFromMultiSelect:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\MultiSelectFromMultiSelect
                        template: 'product/filters/multi_select.html.twig'

                    FilterMultiRelation:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\MultiSelectRelation
                        template: 'product/filters/multi_relation.html.twig'

                    FilterCategory:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\SelectCategory
                        template: 'product/filters/select_category.html.twig'

                    FilterRelation:
                        filter_type_id: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\SearchIndex\SelectRelation
                        template: 'product/filters/object_relation.html.twig'
