parameters:
    secret: 8ghChso+HNQZ/QeLr0TTsSeKKewmODdyVITWATbSZjk=

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    #
    # CONTROLLERS
    #

    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: [ 'controller.service_arguments' ]


    #
    # COMMANDS
    #

    App\Command\:
        resource: '../src/Command/*'
        tags: [ 'console.command' ]

    OpenSearch\Client:
        alias: pimcore.open_search_client.default
        public: true

    App\EventListener\SeoListener:
        tags:
            - { name: kernel.event_subscriber }

    app.custom_filter_service:
        class: Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterService
        arguments:
            - '@Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterGroupHelper'
            - '@Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\NumberRange'
            - '@Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\NumberRangeSelection'
            - '@Pimcore\Bundle\EcommerceFrameworkBundle\FilterService\FilterType\Select'

    App\Ecommerce\PriceSystem\CustomPriceSystem:
        arguments:
            - 'bar'

    app.custom_attribute_price_system:
        class: Pimcore\Bundle\EcommerceFrameworkBundle\PriceSystem\AttributePriceSystem
        arguments:
            $options:
                attribute_name: customPriceField

    Pimcore\Bundle\EcommerceFrameworkBundle\AvailabilitySystem\AvailabilitySystem: ~

    App\Service\CartService:
        public: true