parameters:
    secret: 8ghChso+HNQZ/QeLr0TTsSeKKewmODdyVITWATbSZjk=

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    #
    # CONTROLLERS
    #

    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: [ 'controller.service_arguments' ]


    #
    # COMMANDS
    #

    App\Command\:
        resource: '../src/Command/*'
        tags: [ 'console.command' ]

    OpenSearch\Client:
        alias: pimcore.open_search_client.default
        public: true

    App\EventListener\SeoListener:
        tags:
            - { name: kernel.event_subscriber }