parameters:
    secret: 8ghChso+HNQZ/QeLr0TTsSeKKewmODdyVITWATbSZjk=

    #pimcore_executable_composer: php /opt/vendor/bin/composer.phar
    #pimcore_executable_html2text: /usr/local/html2text/bin/html2text
    #pimcore_executable_soffice: /opt/libreoffice/bin/soffice
    #pimcore_executable_gs: /opt/ghostscript/bin/gs
    #pimcore_executable_pdftotext: /opt/tools/pdftotext
    #pimcore_executable_xvfb-run: /opt/tools/xvfb-run
    #pimcore_executable_pngcrush: /opt/tools/pngcrush
    #pimcore_executable_zopflipng: /opt/tools/zopflipng
    #pimcore_executable_pngout: /opt/tools/pngout
    #pimcore_executable_advpng: /opt/tools/advpng
    #pimcore_executable_cjpeg: /opt/tools/cjpeg
    #pimcore_executable_jpegoptim: /opt/tools/jpegoptim
    #pimcore_executable_php: /usr/local/custom-php/bin/php
    #pimcore_executable_nice: /opt/tools/nice
    #pimcore_executable_nohup: /opt/tools/nohup
    #pimcore_executable_ffmpeg: /opt/tools/ffmpeg
    #pimcore_executable_exiftool: /opt/tools/exiftool
    #pimcore_executable_wkhtmltoimage: /usr/local/bin/wkhtmltoimage
    #pimcore_executable_timeout: /usr/bin/timeout
    #pimcore_executable_facedetect: /usr/bin/facedetect
    # graphviz
    #pimcore_executable_dot: /usr/bin/dot

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    #
    # CONTROLLERS
    #

    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: [ 'controller.service_arguments' ]


    #
    # COMMANDS
    #

    App\Command\:
        resource: '../src/Command/*'
        tags: [ 'console.command' ]

    App\Service\OpenSearchService:
        arguments:
            $openSearchHost: 'host.docker.internal'
            $openSearchPort: '%env(OPENSEARCH_PORT)%'
            $openSearchIndex: '%env(OPENSEARCH_INDEX)%'
            $logger: '@logger'
    
    App\Command\CheckOpenSearchCommand:
        arguments:
            $openSearchClient: '@pimcore.open_search_client.default'
        tags: ['console.command']

    App\EventListener\SeoListener:
        tags:
            - { name: kernel.event_subscriber }